using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace SplitGroupie
{
    public class Defaults
    {
        public Regex _REGEX = new Regex(@"\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\:[0-9]{1,5}\b");
        public List<string> sources = new List<string>();

        public Defaults()
        {
            sources.Add(@"http://free-proxy-list.net/anonymous-proxy.html");
            sources.Add(@"http://proxyape.com/");
            sources.Add(@"http://socks5proxies.com/index.php?page=3&action=freeproxy");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=anonymous&p=5");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=anonymous&p=9");
            sources.Add(@"http://proxytime.ru/http");
            sources.Add(@"http://socks5proxies.com/index.php?page=4&action=freescrapeboxproxies");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=anonymous&p=8");
            sources.Add(@"http://notan.h1.ru/hack/xwww/proxy5.html");
            sources.Add(@"http://notan.h1.ru/hack/xwww/proxy4.html");
            sources.Add(@"http://notan.h1.ru/hack/xwww/proxy2.html");
            sources.Add(@"https://www.us-proxy.org/");
            sources.Add(@"http://www.proxylists.net/http_highanon.txt");
            sources.Add(@"http://socks5proxies.com/index.php?action=freescrapeboxproxies");
            sources.Add(@"http://socks5proxies.com/index.php?page=2&action=freescrapeboxproxies");
            sources.Add(@"http://proxygaz.com/country/united-states-of-america-proxy/");
            sources.Add(@"http://multiproxy.org/anon_proxy.htm");
            sources.Add(@"http://socks5proxies.com/index.php?page=2&action=freeproxy");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=anonymous");
            sources.Add(@"http://txt.proxyspy.net/proxy.txt");
            sources.Add(@"http://files.c75.in/pub/proxy-list.txt");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=anonymous&p=2");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=1");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=2");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=3");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=4");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=5");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=6");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=7");
            sources.Add(@"http://dogdev.net/Proxy/all?after=&working=1");
            sources.Add(@"http://proxy50-50.blogspot.in/feeds/posts/default");
            sources.Add(@"http://blackstarsecurity.com/proxy-list.txt");
            sources.Add(@"http://sslproxies24.blogspot.in/feeds/posts/default");
            sources.Add(@"http://jurnalproxies.blogspot.in/");
            sources.Add(@"http://fr.proxyservers.pro/");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=anonymous&p=7");
            sources.Add(@"http://us-proxy-server.blogspot.in/");
            sources.Add(@"http://code.76lt.com/daili/?dd=niming");
            sources.Add(@"http://notan.h1.ru/hack/xwww/proxy3.html");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=anonymous&p=3");
            sources.Add(@"http://socks5proxies.com/index.php?page=3&action=freescrapeboxproxies");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=anonymous&p=6");
            sources.Add(@"http://guncelproxy.com/Anasayfa/");
            sources.Add(@"http://www.proxylists.net/http.txt");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=13");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=14");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=15");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=16");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=17");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=18");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=19");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=20");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=21");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=22");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=23");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=24");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=25");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=26");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=27");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=28");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=29");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=30");
            sources.Add(@"http://www.rmccurdy.com/scripts/proxy/good.txt");
            sources.Add(@"http://hackingballz.com/proxys/");
            sources.Add(@"http://www.cnproxy.com/proxy1.html");
            sources.Add(@"http://www.cnproxy.com/proxy2.html");
            sources.Add(@"http://proxylists.net/http_highanon.txt");
            sources.Add(@"http://www.proxylists.net/");
            sources.Add(@"http://www.cnproxy.com/proxy3.html");
            sources.Add(@"http://www.cnproxy.com/proxy4.html");
            sources.Add(@"http://www.cnproxy.com/proxy5.html");
            sources.Add(@"http://rebro.weebly.com/proxy-list.html");
            sources.Add(@"http://proxies4google.com/free-proxy-list/");
            sources.Add(@"http://www.proxylisty.com/anonymity/Elite-ip-list-1");
            sources.Add(@"http://www.proxylisty.com/anonymity/Elite-ip-list-2");
            sources.Add(@"http://www.proxylisty.com/anonymity/Elite-ip-list-3");
            sources.Add(@"http://proxyservers.pro/proxy/list/anonymity/anonymous/order/updated/order_dir/desc/page/1");
            sources.Add(@"http://proxyservers.pro/proxy/list/anonymity/elite/order/updated/order_dir/desc/page/1");
            sources.Add(@"http://proxyservers.pro/proxy/list/anonymity/elite/order/updated/order_dir/desc/page/2");
            sources.Add(@"http://proxyservers.pro/proxy/list/anonymity/elite/order/updated/order_dir/desc/page/3");
            sources.Add(@"http://proxyservers.pro/proxy/list/anonymity/elite/order/updated/order_dir/desc/page/4 ");
            sources.Add(@"http://proxyservers.pro/proxy/list/anonymity/elite/order/updated/order_dir/desc/page/5");
            sources.Add(@"http://proxyservers.pro/proxy/list/anonymity/elite/order/updated/order_dir/desc/page/6");
            sources.Add(@"http://proxyservers.pro/proxy/list/anonymity/elite/order/updated/order_dir/desc/page/7");
            sources.Add(@"http://proxyservers.pro/proxy/list/anonymity/elite/order/updated/order_dir/desc/page/8");
            sources.Add(@"http://proxyservers.pro/proxy/list/anonymity/elite/order/updated/order_dir/desc/page/9");
            sources.Add(@"http://proxyservers.pro/proxy/list/anonymity/elite/order/updated/order_dir/desc/page/10");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=anonymous&p=10");
            sources.Add(@"http://fineproxy.org/eng/?p=6#more-6");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=anonymous&p=4");
            sources.Add(@"http://domaingeek.org/static/proxies.txt");
            sources.Add(@"http://proxylist.me/?country=UNITED+STATES&availability=0&protocol=&type=L1");
            sources.Add(@"http://notan.h1.ru/hack/xwww/proxy1.html");
            sources.Add(@"http://rootjazz.com/proxies/proxies.txt");
            sources.Add(@"http://pro1apk.blogspot.in/feeds/posts/default");
            sources.Add(@"http://proxyserverlist-24.blogspot.com/feeds/posts/default");
            sources.Add(@"http://newfreshproxies24.blogspot.com/feeds/posts/default");
            sources.Add(@"http://umbrella-security.blogspot.in/feeds/posts/default");
            sources.Add(@"http://socks5proxies.com/index.php?action=freeproxy");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=8");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=9");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=10");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=11");
            sources.Add(@"http://proxylistchecker.org/proxylists.php?t=elite&p=12");
        }
    }
}
